# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "stc"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "^1.3"
flate2 = "^1.0"
json = "^0.12"
indexmap = "^1.7"
csv = { version = "^1.1", optional = true }
